baseURL = "https://wilfred.githuka.com"
title = "Fundi Willy's Low-Level Electronics Lab"
themesDir = "/home/wilfred/githuka_sites/wilfred.githuka.com/themes/"
theme = "m10c"
paginate = 20

[params]
  author = "Wilfred Githuka"
  description = "Right To Repair. You dont have to replace a broken electronic device. Try Repair It"
  [[params.social]]
    name = "github"
    url = "https://github.com/wilfredgithuka"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/wilfredgithuka"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
